version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    environment:
      - FASTAPI_ENV=${FASTAPI_ENV}   # Pass the environment variable from the .env file
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
